- name: Scale AKS cluster
  hosts: localhost
  connection: local
  vars:
    resource_group: _resource_group_
    location: _location_
    aks_name: _aks_name_
    client_id: _"client_id"_
    client_secret: _"client_secret"_
    aks_version: _aks_version_
  tasks:
  - name: Scaling an existed AKS cluster
    azure_rm_aks:
        name: "{{ aks_name }}"
        location: "{{ location }}"
        resource_group: "{{ resource_group }}"
        dns_prefix: "{{ aks_name }}"
        service_principal:
          client_id: "{{ client_id }}"
          client_secret: "{{ client_secret }}"
        agent_pool_profiles:
          - name: default
            count: 3
            vm_size: Standard_D2_v2