- name: Scale AKS cluster
  hosts: localhost
  connection: local
  vars:
    resource_group: __resource_group__
    location: __location__
    aks_name: __aks_name__
    client_id: __client_id__
    client_secret: __client_secret__
    aks_version: __aks_version__
  tasks:
  - name: Scaling an existed AKS cluster
    azure_rm_aks:
        name: "{{ aks_name }}"
        location: "{{ location }}"
        resource_group: "{{ resource_group }}"
        dns_prefix: "{{ aks_name }}"
        kubernetes_version: "{{aks_version}}"
        service_principal:
          client_id: "{{ client_id }}"
          client_secret: "{{ client_secret }}"
        agent_pool_profiles:
        - name: default
          count: 2
          vm_size: Standard_B2s
          enable_auto_scaling: true
          type: VirtualMachineScaleSets
          mode: System
          max_count: 3
          min_count: 1