- name: Scale AKS cluster
  hosts: localhost
  connection: local
  vars:
    resource_group: __resource_group__
    location: __location__
    aks_name: __aks_name__
    client_id: __"client_id"__
    client_secret: __"client_secret"__
    aks_version: __aks_version__
  tasks:
  - name: Scaling an existed AKS cluster
    azure_rm_aks:
        name: "{{ aks_name }}"
        location: "{{ location }}"
        resource_group: "{{ resource_group }}"
        dns_prefix: "{{ aks_name }}"
        service_principal:
          client_id: "{{ client_id }}"
          client_secret: "{{ client_secret }}"
        agent_pool_profiles:
          - name: default
            count: 3
            vm_size: Standard_D2_v2